# GET İsteği ile kitap listesini almak, uygulamanın kullanıcıya mevcut kitapları gösterebilmesi için gereklidir.
# Get all book
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json



###
# POST İsteği ile yeni bir kitap eklemek, kullanıcıların veri tabanına yeni bilgiler ekleyebilmesini sağlar.
# Creat a book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json


{
    "title": "Harry Pother"
}

###
# Update a book
PUT http://localhost:3001/ HTTP1.1
Content-Type application/json

{
    "title": "Dark Tower"
}

# Delete a book
###
DELETE  HTTP://localhost:3001/books/1.1
Content-Type:application/application/json

